M48
; DRILL file {KiCad (6.0.10-0)} date Monday, 23 January 2023 at 10:06:59
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-01-23T10:06:59+00:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.10-0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X105.0Y-105.0
X105.0Y-145.0
X195.0Y-105.0
X195.0Y-145.0
T0
M30
